# -*- coding: utf-8 -*-
{
    'name': "thomasfleet",
    'summary': """Extend and customize Odoo Fleet module to meet Thomas Solution requirements""",
    'description': """Extend and customize Odoo Fleet module to meet Thomas Solution requirements""",
    'author': "Andrew Bates",
    'website': "http://www.kadabby.com",
    'category': 'Thomas',
    'version': '15.0.1',
    'depends': ['base','fleet','account'],
    'data': [
        'security/thomasfleet_security.xml',
        'security/ir.model.access.csv',
        'views/message_views.xml',
        'views/views.xml',
        'views/lease_views.xml',
        'views/customer_views.xml',
        'views/invoice_views.xml',
        'views/templates.xml',
        'views/product_views.xml',
        #'report/custom_header_template.xml',
        'report/lease_print_template.xml',
        'report/lease_printout.xml',
        'report/invoice_report_template.xml',
        'data/fleet.vehicle.state.csv',
        'data/thomasfleet.lease_status.csv',
        'data/thomasfleet.location.csv',
        'data/thomasfleet.floormaterial.csv',
        'data/thomasfleet.fueltype.csv',
        'data/thomasfleet.seatmaterial.csv',
        'data/thomasfleet.asset_class.csv',
        'data/thomasfleet.insurance_class.csv',
        #'data/thomasfleet.remove_makes.xml',
        #'data/thomasfleet.remove_brands.xml',
        'data/fleet.vehicle.model.brand.csv',
        'data/fleet.vehicle.model.csv',
        'data/thomasfleet.trim.csv',
        'data/thomasfleet.inclusions.csv',
        'data/thomasfleet.accessory_type.csv'
    ],
    'installable': True,
    'auto_install': True,
}
